name: update-gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v6

      - name: Setup Node.js 👷🏻
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Build 🏗️
        run: |
          npm ci
          npm run build

      - name: Deploy gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
